app:
  name: details
http:
  mode: release
  port: 8081
db:
  enable: true
  url: "postgres://root:root@localhost:5432/test?sslmode=disable"
  migrations:
    dir: "/resources/db/migrations"
redis:
  enable: true
  network: "tcp"
  url: "localhost:6379"
log:
  filename: /tmp/details.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true

