app:
  name: test
http:
  host: localhost
  mode: release
  port: 8080
db:
  enable: false
  url: "postgres://root:root@localhost:5432/test?sslmode=disable"
  migrations:
    dir: "/resources/db/migrations"
redis:
  enable: false
  network: "tcp"
  url: "localhost:6379"
log:
  filename: /tmp/details.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
telemetry:
  enable: false
  serviceName: test
  endpoint: "localhost:4317"
  insecure: true
github:
  isEnterprise: false
  keyFile: /resources/github/tmtbehooktest.2022-01-04.private-key.pem
  appId: 162614
  installationID: 21951054


