receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
      thrift_http:
processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  queued_retry:
    num_workers: 4
    queue_size: 100
    retry_on_failure: true
extensions:
  health_check: {}
  zpages: {}
exporters:
  kafka/traces:
    brokers:
      - kafka:9092
    topic: 'otlp_spans'
    protocol_version: 2.0.0

  kafka/metrics:
    brokers:
      - kafka:9092
    topic: 'otlp_metrics'
    protocol_version: 2.0.0
service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [jaeger, otlp]
      processors: [memory_limiter, batch, queued_retry]
      exporters: [kafka/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka/metrics]